export const routes = {
    productDetail:"product",
    landingDetail:"landing",
    cart: "cart",
    checkout: 'checkout',
    articlePage: "article",
    profile: "profile",
    blogPage: "blog",
    login: "login",
    register: "register",
    recovery: "recovery",
    men: "men",
    women: "women",
    kids: "kids",
    catalog: "catalog",
};